jobs:
  include:
    - language: php
      php:
        - 7.3
      services:
        - mysql
      cache:
        directories:
          - node_modules
          - vendor
      before_script:
        - cd ./tick-it-easy-backend
        - cp .env.travis .env
        - sudo mysql -e 'create database tick_it_easy;'
        - composer self-update
        - composer install --prefer-source --no-interaction --dev
        - php artisan key:generate
        - php artisan migrate
        - php artisan db:seed
        - php artisan passport:keys
      script:
        - php artisan test 
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
            secure: "otolihyZ5ZW85Er8zE4AiLwN+x4NlyntfOkOaTvVrVM4NOsLDVlL1dRjvGIwArsQbKlBck50rk0RMD7SDuKr0oLK7xNzIC8YSDSgpvqyhPYgqX6GtFmSb50764k6dV2Wtzs05hVsiMhl85oh6VcDs2G2SPunYzOEBWJOV+OZBFy/cBVt43BRjWqRP3jogq7Dffs7QrLTt27TA4POeIOFoyO9LdI6XAaYPpkBKfL7ZzffvMU+yW5aEiX0/uYj5hd9mQPycgp9X02j6BwyHgZK9WK4mz74/rp9VFpUjIiTz+RTpmRSAFw409qYu9bZ+Fne4cGBjNYQWAgZF/wrRFAK/xrcyq0eIdWu+1Wvc/U5IF2vPuJMLE9bWrQ0McjCiI30oJX2LbeoCMAEqCPNLsGOdiBaias7wobmDlJacBPzDmac+y4R8prUqMZETnFw5EKxVWt2vM1xccUfVxTLC+icU2gFfwemwv+JTKiVeRyAkpus0RfoBmAXcdSHDK8Nc/4sBIU2bCXxGj1oNgwK4TPa8FgFkCLw+9gp/oF//q4Ev/Adm3A1Si19yALqnP9X/yqbL8Riv6faSIbDi1FB9vIK3ti/hSE5otXQndP09NJG2L1we0UGvUg/sBrvZBrSD1JWpfDH6hiBZveWeWZsUG/e7jkO801oj46+GPke6oHDhFs="

        app: tick-it-easy-backend
        on:
          branch: main
        run: 
           - php artisan migrate --force

    - language: node_js
      node_js:
        - '12'

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      cache:
        directories:
          - ./node_modules
      before_script:
        - cd frontend
        - npm install
        - npm run build
      script:
        - npm run test -- --watch=false --no-progress --browsers=HeadlessChrome
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: "P/fQCFxU4VbKYiWpVckPofV4MQ0eTugX1f4303ULLtV0/FmCiQYJOA0mbQzyigNeJM/6dheyEB8OK8UptV0N2SerGA5F55SHBk3saN9rLkHRDjclJ9Rt/jNFSs21W1CV/jMYZZULe8fJfOThf/zIf9lQSKV1YC6//51UbSTv2UuNOHuekDvXt4xUJF7eqndST0t7ViGfbDdTlJf1+O3INPvTs2jwqmciL2qVOzMp19rRG2BE29AklTEt8NRbamd3/1mgOdcPHWim4ETj2llFcgsrUrcm9A2r5DvG2bORvhxSYxd8zwAuCt0LyCNs9ffSR4ZUQKaO/hbUBNn0vGaF8g4jTt8Kx3uLSCk/ToysubqJFq9Vxk5AvBrZ+Gn4B3OwbXecxDj/QjflmRsF8mTcVn1dOnz3n8Sdz9kVbW0ds4GJ7HXw4ceDi5TyTclfDTm3sRxeaT+ZSSworipFCqb4LnNIlcjJZQb5ELoeXYZokFAefEEJFtf998UW55+1ePWPOZ8dqsJJJ5gEyWMZKtiF8n7X5b18SHTEwIaO+JG8BCAfLGFuYlHCaEzv4k62/xymz/Suxi7zSn/FfYFnpV9wQLY28UsXqhJhh2XH0+/ywlQGz9w3bXj0D2zrIbpKt9csJqYjXeza6nqJtahpNNqy5pJ7vqoqHTJcPeNsQJrN2HI="
        app: tick-it-easy-fe
        on:
          branch: main